### ISSUE TITLE
Change to 'Get Involved' link on the left hand side.

### ISSUE THREAD

**Issue by ClaireWyatt** [RSE-leaders/SORSE20#100]
Please could this text go onto the 'Get involved' page too?

I've also changed the text below slightly. Please could this be changed to this on the current page too?

-----------

How do I get involved?

Were you going to submit something to an RSE conference this year? Do you have a project you’d like to share? Is there a talk/workshop/panel you’d like to see happen? Then you’ve found the right place!

You can make a contribution to one of the event types, see our call for submissions and/or suggest an event in the Wishlist that you’d like to see in the series. Take a look at the Topic Bazaar if you have an idea but want to find collaborators before submitting. We’re looking for both technical and soft skills and there are no set themes this year but if a theme emerges, we may group those events together to create a half day event or a run of events over a few weeks.

We encourage submissions from all time zones and will schedule events on a day and at a time that suits the presenter. Events will be recorded so that they can be run multiple times to suit different time zones and encourage those communities to come together to network.

**Comment by Chilipp** [comment]
The content has been updated with 63c80564576ffa58abe4dc18f8e106fd38a9eef1
