### ISSUE TITLE
Issue with What is SORSE? - Series of Online Research Software Events

### ISSUE THREAD

**Issue by ClaireWyatt** [RSE-leaders/SORSE20#136]
_faq/about/01-what-is-sorse.md

When viewing the above page, the left hand menu is different to the landing page left hand menu. For example it has 

FAQ
About
How it works

But on the landing page, this has changed to:

Get involved! 
etc 
etc

Is this deliberate or should the left hand menu list items look like landing page list?

This also appears this way on pages 'format of SORSE', 'Tools', 'Registration and fees', 'attending an event'

**Comment by Chilipp** [comment]
Yes, this is generally the case. We define the sidebar depending on the page you're at. We only keep the very first section about SORSE20 the same for all pages. What you see there, is the FAQ navigation. Also for contact, for instance, the sidebar looks different than on the frontpage
![image](https://user-images.githubusercontent.com/9960249/85307381-223eb480-b4b0-11ea-8cec-88525735fd11.png)

Would you want to see more when navigating through the FAQ @ClaireWyatt?

**Comment by Chilipp** [comment]
The navigation in the sidebar needs to look different on the different pages, as otherwise it would be too much. It also should not change on every individual page.

But if you want to see something appearing more prominent in multiple menus, we can do this easily. Just let me know, what you would like to see.

**Comment by ClaireWyatt** [comment]
I think for the blog post page we should be able to see the rest of the programme pages on the left hand side because it's part of the programme but otherwise okay agreed for the other pages (what is sorse etc) to not have the same left hand menu.
