### ISSUE TITLE
Issue with Wishlist

### ISSUE THREAD

**Issue by ClaireWyatt** [RSE-leaders/SORSE20#138]
_pages/programme/wishlist.md

'Code of Conduct' link is broken. Links back to the same page rather than the CoC page.

**Comment by Chilipp** [comment]
Thanks @ClaireWyatt. Red links are not broken, they are not yet set (we marked them red to highlight that we have to do something here). But I'll fix them, no worries

**Comment by ClaireWyatt** [comment]
Ah sorry! user error= lack of github knowledge.
