### ISSUE TITLE
Decide about content structure

### ISSUE THREAD

**Issue by Chilipp** [RSE-leaders/SORSE20#15]
So far, I just copied the content of the [Google Docs document](https://docs.google.com/document/d/1xIO6N5ETFf9ZQYJOK2GcKEU1m-S21txpT7he4CPjNo0/edit) into the welcome page. I feel like, this is not the best structure...

**Comment by Chilipp** [comment]
hey @vsoch, sorry for being a bit slow on this. I have to admit that I never worked with posts, and I thought they work the same as a collection :sweat_smile: The structure you propose sounds good to me! I think the overhead of having the FAQ as a collection is not that bad. 

Would you be willing (and do have some time) to setup the structure that you propose? Otherwise I can work on it during the weekend.

**Comment by Chilipp** [comment]
Concerning the welcome text on the landing page. What about

Welcome to SORSE20 - A **S**eries of **O**nline **R**esearch **S**oftware **E**vents - our international answer to the COVID-19-induced cancellation of many national RSE conferences. We want to provide an opportunity for RSEs to develop and grow their skills, build new collaborations and engage with RSEs worldwide. This is an open call to all RSEs and anyone involved with research software, worldwide, to propose talks, workshops and other types of online events.

And then link to the FAQ with the [current first paragraph](https://rse-leaders.github.io/SORSE20/#what-is-sorse---series-of-online-research-software-events)

**Comment by vsoch** [comment]
Yeah! Here is how I propose we proceed:

 - First PR: I'll add posts with examples for categories and an archive, and then someone can work on posts with real content.
 - Second PR: Adding an events collection, and rendering into a calendar
 - Third PR: Something with FAQ (I think a data file would be best, but it depends on the length of the answers.) Could someone start a draft of the FAQ so we can think about this?

**Comment by Chilipp** [comment]
Hmm, I thought about having the current sections on the [landing page](https://rse-leaders.github.io/SORSE20/) as part of the FAQ. And I think they would be too lengthy for a data file. We could also put them into an about section as suggested by @TeriForey [above](https://github.com/RSE-leaders/SORSE20/issues/15#issuecomment-640230174), but to me, they read exactly like an FAQ type of thing

**Comment by Chilipp** [comment]
Your suggestions of a first and second PR are, however, nice. I think the first official *announcement* post will be the call for contributions.

**Comment by vsoch** [comment]
@Chilipp I can do some of the items I mentioned, but I am definitely not the person to decide about actual content (I would render dummy content.) Could we please rename the issue to something more specific if it is to be assigned to me, or create new issues for the items you'd like me to cover?

**Comment by Chilipp** [comment]
Yes, we should rename it. This issue is rather about the structure of the content than the content itself

**Comment by Chilipp** [comment]
@vsoch as the first and third PR from https://github.com/RSE-leaders/SORSE20/issues/15#issuecomment-642940625 are already addressed by #60 and #64, shall we merge #60, close this issue and create a new one in favor of the calendar thing (second PR in your comment above)?

**Comment by vsoch** [comment]
Yes that sounds good! Is someone able to provide a dummy list of events so I can work on it?

**Comment by Chilipp** [comment]
Closing this in favor of #75 (and as partly solved via #60 and #64)
