### ISSUE TITLE
Events - need a calendar/sorted list

### ISSUE THREAD

**Issue by TeriForey** [RSE-leaders/SORSE20#37]
Not sure on the best format for this, but we should start the conversation. 

We need to list the upcoming events, possibly as a calendar. They should be sorted by date, those that are in the past should be hidden, and it needs to be easy to edit so we can add new events. We'd probably want to advertise the next one or two events on the main page, as well as make it easy to share the events via all the various channels (twitter, email etc). 

Anyone got any experience doing something like this within github pages?

**Comment by Chilipp** [comment]
closing in favor of #75
