### ISSUE TITLE
Enable CircleCI for RSE-leaders

### ISSUE THREAD

**Issue by Chilipp** [RSE-leaders/SORSE20#53]
We use CircleCI to render static previews of the website in Pull requests. Therefore, CircleCI needs to be granted access to the RSE-leaders repository (public repositories only). If you are not familiar with CircleCI @alysbrett, you could make me a regular member of the RSE-leaders organization, and I will make the request.

- [x] CircleCI enabled by @alysbrett

**Comment by vsoch** [comment]
oh I see, it's a permissions fix that is needed. Carry on! :)
