### ISSUE TITLE
Enable SORSE20 Repo on CircleCI

### ISSUE THREAD

**Issue by Chilipp** [RSE-leaders/SORSE20#55]
- [x] #53 closed
- [x] SORSE20 enabled on CircleCI

**Comment by vsoch** [comment]
Didn't I already add this?

**Comment by vsoch** [comment]
https://github.com/DE-RSE/SORSE20/blob/master/.circleci/config.yml

**Comment by Chilipp** [comment]
sure. but when we transfer this repo to the [RSE-leaders](https://github.com/RSE-leaders/) organization, we have to enable the builds for it (it's not about adding the config.yml)

**Comment by vsoch** [comment]
Understood! Don't mind me, just getting on board with the plan :)
