### ISSUE TITLE
Code of Conduct missing

### ISSUE THREAD

**Issue by Chilipp** [RSE-leaders/SORSE20#65]
from slack by @ClaireWyatt: 

> Hello!, we should have a Code of Conduct for our event and on the website (as reminded to me by @sdruskat yesterday) so here is a link to the CoC from the CW20 online workshop earlier this year.  Is there a volunteer who has a bit of time to amend this slightly?  It really isn't very long and I would do it myself but I'm creating sponsorship packages at the moment and doing research on that. https://www.software.ac.uk/cw20/code-conduct

Volunteers welcomed =)

**Comment by sdruskat** [comment]
CoC is online, closing.
