### ISSUE TITLE
Add a license for website sources and the website text

### ISSUE THREAD

**Issue by bast** [RSE-leaders/SORSE20#79]
It's a very nice website layout and solution and others might be interested in reusing this and for this a license would be good. My recommendation is MIT or BSD for the website sources and CC-BY for the content.

**Comment by bast** [comment]
If others agree with MIT and CC-BY-4.0, then I can add the relevant info to the repository and the website.

**Comment by vsoch** [comment]
We would also be proper to include the original license, as is usually best practice. https://github.com/mmistakes/minimal-mistakes#license
