### ISSUE TITLE
Add privacy policy to the website

### ISSUE THREAD

**Issue by bast** [RSE-leaders/SORSE20#80]
My plan was to take https://coderefinery.org/privacy-policy/ as starting point and submit a pull request. Later we can iterate on it.

**Comment by bast** [comment]
Also needs something about how to not appear in a recording in a Zoom call.

**Comment by bast** [comment]
- SSI events privacy policy: https://www.software.ac.uk/privacy-events 
- SSI website privacy policy: https://www.software.ac.uk/privacy-policy

**Comment by Chilipp** [comment]
Hey @bast! Thanks a lot for working on this! I had a look into the resources you sent. I am really not an expert on this, but I guess the coderefinery works as a good basis. Here are the points that I can think of, maybe @sdruskat wants to add something to it?

#### Website
* We store the contact data of authors and co-authors. And the contact information of the presenting authors will be made public on GitHub and on this website (this is, however, also stated separately in the indico submission form, ping @cc-a).
* We use a Google form to submit to the topic bazaar, but this is also stated separately at https://rse-leaders.github.io/SORSE20/programme/bazaar/#submit
* We (will) provide a link to a wishlist in a site hosted at GWDG. There is no tracking of users there, however, unless you are registered and logged in at GWDG. The [privacy notice](https://www.gwdg.de/data-protection-notice) is only available in German, unfortunately
* We do not track how users move or use our webpage, nor do we have a mailing list to subscribe to. But eventually we should mention that it is hosted with GitHub pages ([Privacy notice](https://help.github.com/en/github/site-policy/github-privacy-statement#github-pages)).

#### participation in an event
* We do not store participants data or contact information (besides everything what zoom does).
* Zoom videos in general zoom calls will be recorded. To avoid this, the video must be turned of. Videos of participants during a webinar will not be recorded, unless you are the presenter. The audio will always be recorded
* we do not record the zoom chat during an event. So one way to avoid being recorded is to not use audio and video, but use the chat instead
* Audio and video recordings will be archived and published at the TIB AV portal (the site https://av.tib.eu/ seems to be down at the moment, so I cannot lookup the privacy notice)

**Comment by Chilipp** [comment]
How do you prefer working on this @bast? Could you make a PR where you just create a file under `_pages/privacy.md`?

**Comment by johanphilips** [comment]
I guess the privacy statement for the website can be brief if we do not store any cookies or have any social media cross-site trackers. To verify, I loaded the website in Brave, and it did not complain :-)

![sorse-brave](https://user-images.githubusercontent.com/67114042/85105885-8e4cbe80-b20b-11ea-8bd0-63062d33851f.PNG)

Regarding personal data, we need indeed to adopt the basic GDPR rules, which give the data subject (here the ones registering for the event) four rights:
- right of information: declare which data you collect and why in an understandable fashion
- right of access: declare how they can access the data if they want to.
- right of rectification: declare how they could demand we delete the data.
- right to object: declare how they can object that we process their data.

I can have a look at your draft and maybe help write it. There are many templates out there for websites like ours and I have been "data protection officer" at our research department, so am quite familiar with the GDPR, though mainly in the context of grant proposals 😄

**Comment by Chilipp** [comment]
Deleting the data is tricky if we store it in GitHub. Do you have experience with that?

**Comment by johanphilips** [comment]
Not on GitHub, just joined yesterday X-D We typically store data in a separate database. In our case here, Google Form data will be collected in a spreadsheet that is version controlled? Maybe keep it out of version control?

Quickly looking a the GitHub Help, there is a way to undo: https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Probably they implemented this for all the people who committed their database passwords on GitHub 🤣

**Comment by bast** [comment]
> How do you prefer working on this @bast? Could you make a PR where you just create a file under `_pages/privacy.md`?

I am unsure yet, I was planning to draft this over the weekend and first need to get overview over the source structure which I haven't done yet.

**Comment by johanphilips** [comment]
The one from Code Refinery is quite brief but might cover most of our data collection. The one of SSI resembles more the standard privacy statement, but also includes cookie policy which we probably will not have. I am fine with starting from the one at Code Refinery.

**Comment by bast** [comment]
I will send a draft-pull request ASAP (probably tomorrow).

**Comment by bast** [comment]
> > How do you prefer working on this @bast? Could you make a PR where you just create a file under `_pages/privacy.md`?
> 
> I am unsure yet, I was planning to draft this over the weekend and first need to get overview over the source structure which I haven't done yet.

But I will probably do exactly this (unless I see a much better way after browsing sources).

**Comment by Chilipp** [comment]
Do we need to mention twitter in the statement as we add the stream to the website (see #86)?

> Quickly looking a the GitHub Help, there is a way to undo: https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Great! Thanks @johanphilips :) I think this should be sufficient. So they can just write a mail and we remove the file with their submission.

@bast: If you need any further input or if anything is unclear, please let me know.

**Comment by bast** [comment]
Draft is up with some questions: #116. I suggest we add suggestions there and iterate there.

**Comment by sdruskat** [comment]
Closed via merging of #116.
