### ISSUE TITLE
Add an Impressum

### ISSUE THREAD

**Issue by Chilipp** [RSE-leaders/SORSE20#91]
Should we add an impress to the site? @rainsworth, I remember that you said during the OC call that you have experience with this, right? What should we add for such an international online event?

**Comment by johanphilips** [comment]
If I understand correctly, an Impressum identifies the owner of the website and is legally obliged in German-speaking countries?

**Comment by johanphilips** [comment]
So we need to identify who owns this website :smile: and then add:
- Name of the website owner and legal representative
- Registered address
- Contact information – email address, phone number?
- VAT number?
- Any additional trade registry or license numbers?

**Comment by knarrff** [comment]
Before we discuss about the German laws: German websites are defined as being published by individuals or organisations that are based in Germany. Does this even apply?

**Comment by johanphilips** [comment]
> Before we discuss about the German laws
I just wanted to indicate that it is only mandatory in those countries.

And yes, these laws probably do not apply, since the SORSE organising committee is behind the website. It does not hurt to add some info anyway. You could also say that, indirectly, the Society of Research Software Engineering is behind this website.

**Comment by Chilipp** [comment]
Alright, then I think we just add the [about](https://rse-leaders.github.io/SORSE20/faq/#about) section to the footer (where you normally see the Impressum) and an FAQ _who is behind SORSE20_. Would this work for you?

**Comment by johanphilips** [comment]
should be sufficient, yes
