### ISSUE TITLE
Suggested Change to landing page

### ISSUE THREAD

**Issue by ClaireWyatt** [RSE-leaders/SORSE20#94]
Could  the 'aims' bullet points go on the landing page too underneant the opening paragraph?

**Comment by Chilipp** [comment]
The _aims_ are pretty long (see screenshot below). I would not link them how they are to the front page. Can I instead propose to change "What is SORSE" in the navigation to "Aims of SORSE"? Or we shorten the aims for the front page.

![image](https://user-images.githubusercontent.com/9960249/85184955-3907c000-b292-11ea-8f11-f2991b622a20.png)

**Comment by ClaireWyatt** [comment]
okay - agree to your suggestions 'Can I instead propose to change "What is SORSE" in the navigation to "Aims of SORSE"?'
