### ISSUE TITLE
Suggested changes to page 'How can I attend an event '

### ISSUE THREAD

**Issue by ClaireWyatt** [RSE-leaders/SORSE20#98]
Could this page also be linked on the left hand side underneath the other pages that I have mentioned in other issues?

Please change the text to:

**Registration**

Registration for each event will be via a simple google form owned by Soc-RSE. All data will be deleted from the form after each event. The data will not be passed to Zoom or Discord. It will be possible to join the Zoom events via a link and a browser therefore no zoom account is needed. The link and password to each event will be emailed to the registered participants an hour before the event is due to start. If you agree for the sponsors to contact you when completing the registration form, the basic information of name and email address will be forwarded to the sponsors.

Events will be recorded so that they can be run multiple times to suit different time zones and encourage communities to come together to network within different regions. A presenter can pre-record their event if they wish and the programme team will provide assistance with this process. For certain events, like workshops and poster sessions, we will be using Zoom breakout rooms which allow for direct interaction with the speaker via audio and video. We will also use Slack space (join here) to allow continuing discussions that will remain available after each individual event.

Webinars will allow speakers to present, share their screen or webcam and attendees will have the opportunity to ask questions and answer polls via the built-in Q&A system of Zoom webinars. Questions will then be read out in the Q&A part of the session and answered live by the speakers. 

-------
The link for 'slack space (join here)' is https://docs.google.com/forms/d/e/1FAIpQLSc9LqOWGwA1xDvSgy81eimcb9s0cNBFso0zv0_HoZz16G1M5w/viewform?c=0&w=1

**Comment by ClaireWyatt** [comment]
And please could we change it to 'Attending an event' for the title

**Comment by Chilipp** [comment]
Do you really want to add the registration information here and on the _Registration and Fees_ page? (see #109). I'd link one to the other @ClaireWyatt
